import logging
import json
import os
from dataclasses import dataclass, field, asdict
from typing import Annotated
from datetime import datetime

from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentSession,
    JobContext,
    JobProcess,
    MetricsCollectedEvent,
    RoomInputOptions,
    WorkerOptions,
    cli,
    metrics,
    tokenize,
    function_tool,
    RunContext
)
from livekit.plugins import murf, silero, google, deepgram, noise_cancellation
from livekit.plugins.turn_detector.multilingual import MultilingualModel

logger = logging.getLogger("agent")

load_dotenv(".env.local")

# Path to wellness log file
WELLNESS_LOG_FILE = "wellness_log.json"


@dataclass
class WellnessCheckIn:
    """Represents a single wellness check-in session"""
    date: str
    mood: str = ""  # User's self-reported mood
    energy_level: str = ""  # User's energy level
    stress_factors: list[str] = field(default_factory=list)  # Things causing stress
    daily_objectives: list[str] = field(default_factory=list)  # 1-3 goals for the day
    agent_summary: str = ""  # Brief summary generated by agent
    
    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization"""
        return asdict(self)


class WellnessLog:
    """Manages persistence of wellness check-ins"""
    
    def __init__(self, file_path: str = WELLNESS_LOG_FILE):
        self.file_path = file_path
        self.entries: list[WellnessCheckIn] = []
        self.load()
    
    def load(self):
        """Load existing wellness log from JSON file"""
        if os.path.exists(self.file_path):
            try:
                with open(self.file_path, 'r') as f:
                    data = json.load(f)
                    self.entries = [WellnessCheckIn(**entry) for entry in data]
                logger.info(f"Loaded {len(self.entries)} wellness check-ins from {self.file_path}")
            except Exception as e:
                logger.error(f"Error loading wellness log: {e}")
                self.entries = []
        else:
            logger.info(f"No existing wellness log found at {self.file_path}")
            self.entries = []
    
    def save(self):
        """Save wellness log to JSON file"""
        try:
            with open(self.file_path, 'w') as f:
                json.dump([entry.to_dict() for entry in self.entries], f, indent=2)
            logger.info(f"Saved {len(self.entries)} wellness check-ins to {self.file_path}")
        except Exception as e:
            logger.error(f"Error saving wellness log: {e}")
    
    def add_entry(self, entry: WellnessCheckIn):
        """Add a new check-in entry"""
        self.entries.append(entry)
        self.save()
    
    def get_last_entry(self) -> WellnessCheckIn | None:
        """Get the most recent check-in"""
        return self.entries[-1] if self.entries else None
    
    def get_recent_entries(self, count: int = 7) -> list[WellnessCheckIn]:
        """Get the most recent N entries"""
        return self.entries[-count:] if self.entries else []


class WellnessCompanion(Agent):
    def __init__(self) -> None:
        super().__init__(
            instructions="""You are Wellness Companion, a warm, supportive, and grounded daily wellness check-in assistant.
            
            Your personality:
            - Caring, empathetic, and genuinely interested in the user's wellbeing
            - Non-judgmental and supportive, never diagnostic or clinical
            - You help users reflect on their day and set realistic, achievable goals
            - You keep conversations natural, conversational, and concise for voice interaction
            - You NEVER use emojis, asterisks, or complex formatting in your responses
            
            Your workflow for daily check-ins:
            1. Greet the user warmly and check if they have time for a quick wellness check-in
            2. If there are previous check-ins, use get_previous_checkin to reference their last session
            3. Ask about their current mood and how they're feeling
            4. Ask about their energy level today
            5. Gently inquire about any stress factors or things on their mind
            6. Ask what 1-3 goals or intentions they have for today
            7. Offer simple, realistic advice or reflections based on what they share
            8. Provide a brief recap of their mood and objectives
            9. Confirm if the recap sounds accurate
            10. Use save_checkin to persist the check-in data
            11. End with encouraging words
            
            Important guidelines:
            - Always be supportive and non-judgmental
            - NEVER provide medical advice or diagnoses
            - Keep suggestions practical, small, and actionable (e.g., 'take a 5-minute walk', 'try deep breaths')
            - Reference previous check-ins when available to show continuity
            - If user mentions concerning symptoms, gently suggest they speak with a healthcare professional
            - Break large goals into smaller, manageable steps
            - Encourage self-care and realistic expectations
            """,
        )
        self.wellness_log = WellnessLog()
        self.current_checkin = WellnessCheckIn(date=datetime.now().isoformat())

    @function_tool
    async def get_previous_checkin(self, context: RunContext) -> str:
        """Get information about the user's most recent wellness check-in. Use this at the start of a new session to provide continuity.
        
        Returns:
            Summary of the last check-in or message if none exists
        """
        logger.info("Retrieving previous check-in")
        last_entry = self.wellness_log.get_last_entry()
        
        if not last_entry:
            return "This appears to be your first check-in with me. I'm excited to get to know you!"
        
        summary_parts = [f"Last time we talked on {last_entry.date.split('T')[0]}"]
        
        if last_entry.mood:
            summary_parts.append(f"you mentioned feeling {last_entry.mood}")
        
        if last_entry.energy_level:
            summary_parts.append(f"with {last_entry.energy_level} energy")
        
        if last_entry.daily_objectives:
            objectives_str = ", ".join(last_entry.daily_objectives)
            summary_parts.append(f"Your goals were: {objectives_str}")
        
        return ". ".join(summary_parts) + "."

    @function_tool
    async def record_mood(self, context: RunContext, mood: Annotated[str, "User's self-reported mood or how they're feeling"]) -> str:
        """Record the user's current mood. Use this when they describe how they're feeling.
        
        Args:
            mood: Description of their current mood
        
        Returns:
            Acknowledgment message
        """
        logger.info(f"Recording mood: {mood}")
        self.current_checkin.mood = mood
        return f"I hear you're feeling {mood}. Thank you for sharing that with me."

    @function_tool
    async def record_energy_level(self, context: RunContext, energy: Annotated[str, "User's energy level (e.g., 'low', 'moderate', 'high', or descriptive)"]) -> str:
        """Record the user's current energy level. Use this when they describe their energy.
        
        Args:
            energy: Description of their energy level
        
        Returns:
            Acknowledgment message
        """
        logger.info(f"Recording energy level: {energy}")
        self.current_checkin.energy_level = energy
        return f"Got it, your energy is {energy} today."

    @function_tool
    async def record_stress_factors(self, context: RunContext, factors: Annotated[list[str], "List of things causing stress or concern"]) -> str:
        """Record stress factors or concerns the user mentions. Use this when they talk about what's on their mind.
        
        Args:
            factors: List of stressors or concerns
        
        Returns:
            Acknowledgment message
        """
        logger.info(f"Recording stress factors: {factors}")
        self.current_checkin.stress_factors.extend(factors)
        
        if len(factors) == 1:
            return f"I understand that {factors[0]} is weighing on you."
        else:
            return f"I hear you. That's quite a bit to manage - {', '.join(factors)}."

    @function_tool
    async def record_daily_objectives(self, context: RunContext, objectives: Annotated[list[str], "List of 1-3 goals or intentions for the day"]) -> str:
        """Record the user's daily goals or intentions. Use this when they share what they want to accomplish.
        
        Args:
            objectives: List of goals or intentions (ideally 1-3 items)
        
        Returns:
            Confirmation message
        """
        logger.info(f"Recording daily objectives: {objectives}")
        self.current_checkin.daily_objectives = objectives
        
        obj_summary = "\n".join([f"{i+1}. {obj}" for i, obj in enumerate(objectives)])
        return f"Here's what you're focusing on today:\n{obj_summary}\n\nThose sound like solid goals!"

    @function_tool
    async def save_checkin(self, context: RunContext, summary: Annotated[str, "Brief agent-generated summary of the check-in"]) -> str:
        """Save the completed check-in to the wellness log. Use this at the end of the check-in session.
        
        Args:
            summary: A brief summary of the check-in session
        
        Returns:
            Confirmation message
        """
        logger.info("Saving wellness check-in")
        self.current_checkin.agent_summary = summary
        self.wellness_log.add_entry(self.current_checkin)
        
        return f"I've saved today's check-in. I'll remember this for next time. Take care of yourself today!"


def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load()


async def entrypoint(ctx: JobContext):
    # Logging setup
    # Add any other context you want in all log entries here
    ctx.log_context_fields = {
        "room": ctx.room.name,
    }

    # Create agent instance that will be reused
    wellness_agent = WellnessCompanion()

    # Set up a voice AI pipeline using OpenAI, Cartesia, AssemblyAI, and the LiveKit turn detector
    session = AgentSession(
        # Speech-to-text (STT) is your agent's ears, turning the user's speech into text that the LLM can understand
        # See all available models at https://docs.livekit.io/agents/models/stt/
        stt=deepgram.STT(model="nova-3"),
        # A Large Language Model (LLM) is your agent's brain, processing user input and generating a response
        # See all available models at https://docs.livekit.io/agents/models/llm/
        llm=google.LLM(
                model="gemini-2.5-flash",
            ),
        # Text-to-speech (TTS) is your agent's voice, turning the LLM's text into speech that the user can hear
        # See all available models as well as voice selections at https://docs.livekit.io/agents/models/tts/
        tts=murf.TTS(
                voice="en-US-matthew", 
                style="Conversation",
                tokenizer=tokenize.basic.SentenceTokenizer(min_sentence_len=2),
                text_pacing=True
            ),
        # VAD and turn detection are used to determine when the user is speaking and when the agent should respond
        # See more at https://docs.livekit.io/agents/build/turns
        turn_detection=MultilingualModel(),
        vad=ctx.proc.userdata["vad"],
        # allow the LLM to generate a response while waiting for the end of turn
        # See more at https://docs.livekit.io/agents/build/audio/#preemptive-generation
        preemptive_generation=True,
    )

    # To use a realtime model instead of a voice pipeline, use the following session setup instead.
    # (Note: This is for the OpenAI Realtime API. For other providers, see https://docs.livekit.io/agents/models/realtime/))
    # 1. Install livekit-agents[openai]
    # 2. Set OPENAI_API_KEY in .env.local
    # 3. Add `from livekit.plugins import openai` to the top of this file
    # 4. Use the following session setup instead of the version above
    # session = AgentSession(
    #     llm=openai.realtime.RealtimeModel(voice="marin")
    # )

    # Metrics collection, to measure pipeline performance
    # For more information, see https://docs.livekit.io/agents/build/metrics/
    usage_collector = metrics.UsageCollector()

    @session.on("metrics_collected")
    def _on_metrics_collected(ev: MetricsCollectedEvent):
        metrics.log_metrics(ev.metrics)
        usage_collector.collect(ev.metrics)

    async def log_usage():
        summary = usage_collector.get_summary()
        logger.info(f"Usage: {summary}")

    ctx.add_shutdown_callback(log_usage)

    # Add auto-save on disconnect to ensure data isn't lost
    async def auto_save_on_disconnect():
        """Save the current check-in even if conversation was incomplete"""
        if wellness_agent.current_checkin.mood or wellness_agent.current_checkin.energy_level:
            # Only save if at least some data was collected
            if not wellness_agent.current_checkin.agent_summary:
                # Generate a simple summary if agent didn't create one
                wellness_agent.current_checkin.agent_summary = "Incomplete check-in - connection ended early"
            wellness_agent.wellness_log.add_entry(wellness_agent.current_checkin)
            logger.info("Auto-saved incomplete check-in on disconnect")
    
    ctx.add_shutdown_callback(auto_save_on_disconnect)

    # # Add a virtual avatar to the session, if desired
    # # For other providers, see https://docs.livekit.io/agents/models/avatar/
    # avatar = hedra.AvatarSession(
    #   avatar_id="...",  # See https://docs.livekit.io/agents/models/avatar/plugins/hedra
    # )
    # # Start the avatar and wait for it to join
    # await avatar.start(session, room=ctx.room)

    # Start the session, which initializes the voice pipeline and warms up the models
    await session.start(
        agent=wellness_agent,
        room=ctx.room,
        room_input_options=RoomInputOptions(
            # For telephony applications, use `BVCTelephony` for best results
            noise_cancellation=noise_cancellation.BVC(),
        ),
    )

    # Join the room and connect to the user
    await ctx.connect()


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint, prewarm_fnc=prewarm))
